Fix dropdown flashing when input clicked
darrenjennings/vue-autosuggest pull request #29
Opened 2018-02-20 21:10 UTC by STUkh

**What**:

**Why**:

**How**:

**Checklist**:

- [ ] Documentation
- [ ] Tests
- [ ] Ready to be merged 
- [ ] Added myself to contributors table

2018-02-20 23:35 UTC, darrenjennings commented
Thanks for contributing @STUkh! I will work on reviewing this in a bit.

2018-02-21 04:31 UTC, darrenjennings commented on src/Autosuggest.vue
> +      const isChild = isDescendant(this.$el, e.target);
`isDescendant` can be removed in favor of native `.contains` method. 

Please refactor to `this.$el.contains(e.target);`, remove `isDescendant` function from utils and I will approve!

2018-02-22 06:48 UTC, darrenjennings requested changes
@STUkh see comment on PR. Will approve after changes are made! Thanks!

2018-03-14 00:02 UTC, darrenjennings commented
@STUkh can you update this? I would like to merge, but if you don't respond I will apply the fix.

2018-03-14 08:17 UTC, STUkh commented
@darrenjennings sorry, can't do that for a few weeks. Feel free to close and re-apply by yourself

2018-03-23 17:35 UTC, darrenjennings commented
Duplicate of #33

2018-03-23 17:35 UTC, closed without merging